name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 14
          - 16
          - 17

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm clean-install

      - name: Compile CJS bundle
        run: npm run compile

      - name: Test CJS package loading
        run: node -e "console.log(require('.').default('1980').next().year)"

      - name: Run tests
        run: npm run coverage

      - name: Upload coverage results
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.node == '16'
