name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 'v22'
          - 'v23'
          - 'v24'
          - 'v25'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm clean-install
      - name: Test CommonJS package loading
        run: node -e "console.log(require('.').default('1980').next().year)"
      - name: Run tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint

  coverage:
    needs: [test, lint]
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm clean-install
      - name: Run tests with coverage
        run: npm run coverage
      - name: Upload coverage results
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
